[package]
name = "imaged"
version = "0.1.0"
description = "Image processing server"
authors = ["Ryan Fowler <ryan.fowler19@gmail.com>"]
repository = "https://github.com/ryanfowler/imaged"
license = "MIT"
edition = "2021"

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = 3
strip = true

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 2

[dependencies]
ahash = "0.8.7"
anyhow = "1.0.79"
axum = { version = "0.7.4", features = ["query"] }
base64 = "0.21.6"
bytes = "1.5.0"
image = { version = "0.24.8", default-features = false, features = ["avif-encoder", "png", "tiff"] }
jemallocator = { version = "0.5.4" }
kamadak-exif = "0.5.5"
libavif-image = { version = "0.11.0", default-features = false, features = ["codec-dav1d"] }
lru = "0.12.1"
memchr = "2.7.1"
reqwest = "0.11.23"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
thumbhash = "0.1.0"
tokio = { version = "1.35.1", features = ["rt", "net", "macros", "signal", "sync"] }
turbojpeg = { version = "0.5.4", features = ["image"] }
webp = "0.2.6"
