[package]
name = "imaged"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = 3
strip = true

[dependencies]
anyhow = "*"
axum = { version = "*", features = ["query"] }
bytes = "*"
image = { version = "*", default-features = false, features = ["avif-encoder", "png", "tiff"] }
jemallocator = { version = "*" }
kamadak-exif = "*"
libavif-image = "*"
reqwest = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
tokio = { version = "*", features = ["rt", "net", "macros", "signal", "sync"] }
turbojpeg = { version = "*", features = ["image"] }
webp = "*"
